services:
  web:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: web
    restart: always
    expose:
      - "80"
    networks:
      - darknet

  tor:
    image: dperson/torproxy
    container_name: tor-hidden-service
    volumes:
      - ./tor/torrc:/etc/tor/torrc
      - ./tor/data:/var/lib/tor/hidden_service
    networks:
      - darknet
    command: -f /etc/tor/torrc
    restart: unless-stopped

networks:
  darknet:
    driver: bridge
