---
- hosts: vps
  vars:
    repo_dir: "{{ ansible_env.HOME }}/dark-web"
    repo_url: "https://github.com/MementoMori11723/dark-web.git"

  tasks:
    - name: Ensure the repo is cloned and updated
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        version: master
        update: yes
        force: yes

    - name: Run `make stop`
      command: make stop
      args:
        chdir: "{{ repo_dir }}"

    - name: Run `make`
      command: make
      args:
        chdir: "{{ repo_dir }}"
